### ISSUE TITLE
Currency highlighting not working if `hledger-currency-string' is changed

### ISSUE THREAD

**Issue by RosalesJ** [narendraj9/hledger-mode#24] opened 2018-08-15 21:07 UTC
## Versions
emacs: 26.1
hledger-mode: master branch

## Reproduce
In config: 
```lisp 
(setq hledger-currency-string "£") 
```
## Issue
Without setting `hledger-currency-string'
![current](https://user-images.githubusercontent.com/17154302/44173349-9edefb80-a0ad-11e8-9b48-e460c8f6158c.png)

With setting changed:
![current](https://user-images.githubusercontent.com/17154302/44173217-40b21880-a0ad-11e8-9cb5-85d6a6a4b054.png)

**Comment by narendraj9** [comment] 2018-08-18 18:08
Thanks for reporting this. I will check the issue. :)

**Comment by narendraj9** [comment] 2018-08-19 11:47
The reason for this is that the regex is derived from `hledger-currency-string` variable during load time. So, I think to workaround this bug at the moment, you can just set the variable before calling `(require 'hledger-mode)`. I have not tested this. You can probably try and let me know.

**Comment by RosalesJ** [comment] 2018-08-19 15:08
This doesn't seem to work, the variable is undefined before ```(require 'hledger-mode)``` and is overwritten after it is called

**Comment by narendraj9** [comment] 2018-08-19 20:27
It should work actually. That's because you can just do `(setq var value)` and it comes to existence. Any new `defvar` or `defcustom` for the variable do not affect its value. Thanks for trying out. I will check and fix the issue.

**Comment by narendraj9** [comment] 2018-08-19 20:28
It should work actually. That's because you can just do `(setq var value)` and it comes to existence. Any new `defvar` or `defcustom` for the variable do not affect its value. Thanks for trying out. I will check and fix the issue.

**Comment by narendraj9** [comment] 2018-08-21 14:33
https://github.com/narendraj9/hledger-mode/commit/af51c0a7a0952c244e5c6bb818ab4ce3b9806609 should fix the issue.

**Comment by RosalesJ** [comment] 2018-08-21 21:43
This seem like it would fix the issue for me, it doesn't though.

Here is a screenshot before ```(setq hledger-currency-string "＄")```
![current](https://user-images.githubusercontent.com/17154302/44428006-18209780-a561-11e8-8672-9a887b8e1458.png)

Here is a screenshot after ```(setq hledger-currency-string "＄")```
![current](https://user-images.githubusercontent.com/17154302/44428057-456d4580-a561-11e8-82c4-a6886bb5745a.png)

**Comment by narendraj9** [comment] 2018-08-22 05:55
After you set the variable `hledger-currency-string`, you need to open a new buffer that goes into `hledger-mode`. That causes the font-lock settings for the buffer to be revised. Did you do that for the above?

**Comment by RosalesJ** [comment] 2018-08-23 16:18
Yes, I restarted emacs between these screenshots.  I'm using a full width dollar sign ([＄](http://graphemica.com/%EF%BC%84)) instead of a normal dollar sign ([$](http://graphemica.com/$)) as a temporary workaround for #23. When I tried the normal dollar sign highlighting worked fine–however trying other currencies such as € and £ also caused the highlighting to fail.

**Comment by narendraj9** [comment] 2018-08-26 14:40
I think the issue is that hledger-mode higlights only one currency at a time. That's a limitation. I think we can borrow something from `ledger-mode` about this. You can also try `ledger-mode`.

**Comment by RosalesJ** [comment] 2018-08-28 19:05
I don't believe this is the issue–I'm not trying to highlight multiple currencies at the same time.  The issue is that ```hledger-mode``` currency highlighting breaks for most currency signs including € and £.

**Comment by narendraj9** [comment] 2018-08-31 14:11
I have not been able to look into this for the time being. Might take me some time to get to this. If you are willing to spend time fixing this, I think you can start with changing this regex that should match an amount with the currency string: https://github.com/narendraj9/hledger-mode/blob/af51c0a7a0952c244e5c6bb818ab4ce3b9806609/hledger-core.el#L73  This is then passed onto font-lock in `hledger-mode` setup.

**Comment by narendraj9** [comment] 2020-06-14 12:21
Please check if the referenced PR fixes the issue. Closing this one again for now. Feel free to re-open.

**Closed by narendraj9** 2020-06-14 12:21 UTC
